### ISSUE TITLE
The `frame` method in managers.py has a bug

### ISSUE THREAD

**Issue by indrajitsg** [PacktPublishing/Learning-OpenCV-4-Computer-Vision-with-Python-Third-Edition#12]
The cameo code doesn't work unless the `frame` method in `managers.py` is updated as:

```
@property
def frame(self):
    if self._enteredFrame:
        _, self._frame = self._capture.retrieve(self._enteredFrame, self.channel)
        return self._frame
```

**Comment by JoeHowse** [comment]
Hello, and thank you for the query. The Cameo demo code does work for me with the current version of the `frame` method, as follows:

```
    @property
    def frame(self):
        if self._enteredFrame and self._frame is None:
            _, self._frame = self._capture.retrieve(
                    self._frame, self.channel)
        return self._frame
```

Note that `frame` is not intended to return a new frame every time it is called.  It is intended to return a frame that was grabbed the last time `enterFrame` was called.  See Chapter 2 for details about the distinction between `grab` and `retrieve`, and for details about the order of method calls in the demo.
