### ISSUE TITLE
Modifying for different OpenNI compliant devices

### ISSUE THREAD

**Issue by redbarn7** [PacktPublishing/Learning-OpenCV-4-Computer-Vision-with-Python-Third-Edition#13]
Hello,
I have been enjoying your book and learning alot from it.  But I have become stuck trying to understand how to modify the code for a different openni camera.  A significant part is my own ignorance around drilling back through the stack to understand what is being called from where.  I am not even sure which OpenCV is being called... Maybe a good Packt course would be understanding and using Visual Studio Code or other programming environment to allow understanding of the software stack. 
Thanks.

**Comment by JoeHowse** [comment]
Thank you for the comment! I am glad to hear that the book has been helpful.

In general, knowledge of CMake and your platform's C++ toolchain (for example, Visual C++ on Windows) will help you dive deeper into the software stack of OpenCV and many other open-source libraries. I agree that these would be good topics for a future book or course. I find that I do more and more tinkering with library internals as time goes by...

Within the OpenCV source code, [`cap_openni2.cpp`](https://github.com/opencv/opencv/blob/4.x/modules/videoio/src/cap_openni2.cpp) is where OpenNI camera support resides. However, I believe OpenNI itself is not maintained much anymore, so you may find it difficult to support new cameras through this route.

More recently, many OpenCV developers have adopted the OAK-D depth cameras, which have their own Python API. You can find samples in Chapters 4 and 10 of the (early-access) [repository for our upcoming book](https://github.com/PacktPublishing/Learning-OpenCV-5-Computer-Vision-with-Python-Fourth-Edition/tree/main), Learning OpenCV 5 Computer Vision with Python.

As part of OpenCV 5, an overhaul of 3D camera support is promised. However, this next version of the library is still work-in-progress.
