### ISSUE TITLE
Chapter 05 Bug in the sample face_recognition.py script (I'm using python 3.8)

### ISSUE THREAD

**Issue by everglow01** [PacktPublishing/Learning-OpenCV-4-Computer-Vision-with-Python-Third-Edition#14]
![image](https://github.com/PacktPublishing/Learning-OpenCV-4-Computer-Vision-with-Python-Third-Edition/assets/155972933/5fb582db-a06d-4851-9c46-64b173f27681)

91：except IOError, (errno, strerror):
The except statement here uses a comma instead of 'as', maybe it's python2 syntax here, but nowadays opencv4 doesn't support the old python syntax anymore.

And thanks for the book, it's been a great help!🥹🤗

**Comment by JoeHowse** [comment]
Thanks for the report! I have pushed a fix now:

```
                except IOError as err:
                    errno, strerror = err.args
```

I am happy to hear that the book has been helpful to you!
