### ISSUE TITLE
Is it should be "roi_gray=gray[y:y+h,x:x+w]"

### ISSUE THREAD

**Issue by xyzxyzxyzxyzxz** [PacktPublishing/Learning-OpenCV-4-Computer-Vision-with-Python-Third-Edition#15]
In chapter5, file "face_recognition_video.py", line 50, is it should be "roi_gray=gray[y:y+h,x:x+w]", not "roi_gray = gray[x:x+w, y:y+h]" ?

**Comment by JoeHowse** [comment]
You are correct. I have pushed the fix. Thanks for the report!
