### ISSUE TITLE
Problem compiling OpenCV with VStudio

### ISSUE THREAD

**Issue by Robibe** [PacktPublishing/Learning-OpenCV-4-Computer-Vision-with-Python-Third-Edition#9]
Dear Forum

Following the book instruction, i load in VS the OpenCV.sln , select - Release - x64, and build.

The build process show me   183 steps, all ok  apart 1, the 134, that give me this fatal error:

134>C:\OpenCV\opencv\sources\modules\python\src2\cv2.cpp(17,10): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
134>Done building project "opencv_python3.vcxproj" -- FAILED.

The total result is this:
= Build: 172 succeeded, 1 failed, 0 up-to-date, 10 skipped ====

Other info:
The OpenVC is the 4.5.4.
VS is the comunity 2019
Python 3.10.2 (tipyng python on terminal i get this reply)

So, what can i do.
Thanks
Roberto

**Comment by JoeHowse** [comment]
Hi Roberto,

It seems that OpenCV's CMake script did not successfully locate your Python installation. Please re-run CMake with the following changes:

- Make sure that you are using the correct paths with the `-DPYTHON3_LIBRARY` and `DPYTHON3_INCLUDE_DIR` CMake flags.
- Alternatively, if you have installed Python in the default location, you can probably remove the `-DPYTHON3_LIBRARY` and `DPYTHON3_INCLUDE_DIR` CMake flags.

Check the output of CMake to see whether it reports that it found Python 3.10.

I hope this helps.

Best regards,

Joe

**Comment by Robibe** [comment]
Thanks for reply Mr Howse

I find the include folder under:

C:\Users\Roberto\AppData\Local\Programs\Python\Python310\include

and the .lib under:

C:\Users\Roberto\AppData\Local\Programs\Python\Python310\libs\python310.lib

So i modified the command following the first of your suggestion(I add spaces for a better view):

cmake -DCMAKE_BUILD_TYPE=RELEASE             
-DOPENCV_SKYP_PYTHON_LOADER=ON                         
 -DPYTHON3_LIBRARY=C:\Users\Roberto\AppData\Local\Programs\Python\Python310\libs\python310.lib

-DPYTHON3_INCLUDE_DIR=C:\Users\Roberto\AppData\Local\Programs\Python\Python310\include                 -DWITH_OPENNI2=ON

-DOPENCV_EXTRA_MODULES_PATH=C:/OpenCV_Contrib/modules                      -DOPENCV_ENABLE_MONFREE=ON                     -G”Visual Studio 16 2019” -A x64  C:/OpenCV/opencv/sources

The result show me something  good (as before):
-- Configuring done
-- Generating done
-- Build files have been written to: C:/OpenCV_Build

BUT, in the middle, show me a Python37 folder that I dont have on my PC:

Hope some help again.
Thanks
Roberto

**Comment by JoeHowse** [comment]
Hi Roberto,

Here are a few suggestions that may help.

Please try OpenCV 4.5.5 (currently the latest version) and opencv_contrib 4.5.5, just in case they contain any bugfixes relating to compatibility with recent Python versions.

If you have previously had any other Python version installed (such as Python 3.7), please ensure that it it uninstalled and that its paths are removed from your environment variables.

Please try the following simplified CMake command (spaces added for clarity):

cmake -DCMAKE_BUILD_TYPE=RELEASE
-DWITH_OPENNI2=ON
-DOPENCV_EXTRA_MODULES_PATH=C:/OpenCV_Contrib/modules
-DOPENCV_ENABLE_MONFREE=ON -G”Visual Studio 16 2019”
-A x64
C:/OpenCV/opencv/sources

(Thus, we are removing the extra flags about Python. Normally, if Python is installed to the default location, OpenCV will find it successfully without any CMake flags.)

Please let me know your results and, if the problem persists, attach a text file containing the CMake output.

Best regards,

Joe

**Comment by Nazaroadi** [comment]
Dear Forum

Please forgive my poor English. I'm reader from China

When I follow the instructions and run cameo.py ,there is a "type error" says TypeError: CaptureManager() takes no arguments
Then I checked my code ,didnt find any mistakes.

Other info:
Python 3.9.1 

So, what can i do.
Thanks
Frizzle

**Comment by JoeHowse** [comment]
Hi Frizzle,

Please try the latest version of the code from this repository to see whether the issue has been resolved. `cameo.py` and the related scripts work for me in Python 3.9.9 and OpenCV 4.5.5.

Thanks,

Joe
